server:
  port: 9001
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true 
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health
oracle:
  database: 10g from cloud server
  username: prathiksh
  password: feb@2022
---
spring:
  config:
    activate:
      on-profile: test
oracle:
   database: 11g from cloud server
   
  
  
    
